name: Deploy Flask App to VPS (Password SSH)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests (optional)
        run: |
          echo "Running unit tests..."
          # e.g., pytest

      - name: Deploy using SSH password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/Tests
            git pull origin main
            docker-compose down
            docker-compose up -d --build
